// <auto-generated />
using System;
using GameStore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240808190550_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("02e73b48-bf3e-45df-a107-c65f302ce8dc"),
                            Name = "RTS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("03e73b48-bf3e-45df-a107-c65f302ce8dd"),
                            Name = "TBS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("04e73b48-bf3e-45df-a107-c65f302ce8de"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("05e73b48-bf3e-45df-a107-c65f302ce8df"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("07e73b48-bf3e-45df-a107-c65f302ce8e1"),
                            Name = "Rally",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("08e73b48-bf3e-45df-a107-c65f302ce8e2"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("09e73b48-bf3e-45df-a107-c65f302ce8e3"),
                            Name = "Formula",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("10e73b48-bf3e-45df-a107-c65f302ce8e4"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("12e73b48-bf3e-45df-a107-c65f302ce8e6"),
                            Name = "FPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("13e73b48-bf3e-45df-a107-c65f302ce8e7"),
                            Name = "TPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("14e73b48-bf3e-45df-a107-c65f302ce8e8"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("15e73b48-bf3e-45df-a107-c65f302ce8e9"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01f73b48-bf3e-45df-a107-c65f302ce8fa"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("02f73b48-bf3e-45df-a107-c65f302ce8fb"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("03f73b48-bf3e-45df-a107-c65f302ce8fc"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("04f73b48-bf3e-45df-a107-c65f302ce8fd"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Publisher");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
