// <auto-generated />
using System;
using GameStore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240719182804_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Entity.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Data.Entity.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameStore.Data.Entity.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Entity.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("3ceceaff-a1a9-44b9-9880-9c3fba5d7fb0"),
                            Name = "RTS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("49ae79b8-96fb-47f7-92e2-14792a12dcad"),
                            Name = "TBS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("2f37a868-c790-4db5-b16f-85c24c28ca87"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("8d784d3e-3ec5-4357-951e-b85aabb7f557"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("8b9e34ec-64e3-4133-8502-b4d845b55a81"),
                            Name = "Rally",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("7af3d57d-a9f3-4b35-8d70-2c9b6a887fa0"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("ea309af0-051d-4ab9-9a7f-9e2f87e170fb"),
                            Name = "Formula",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("ed782957-6a7a-4119-8e72-924abafe8519"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("382e7c5d-324b-41c2-ba7f-1c01cc5470c8"),
                            Name = "FPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("8f355ccd-5e7d-4668-a6e4-ce3eb22b91c8"),
                            Name = "TPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("7fcbd360-65bc-4704-9cb1-f0f02e460465"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("49ed8216-98df-490c-b725-a257edeec6bf"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entity.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc807cf9-4bf6-4639-adbd-93db620a1dad"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("ccc88a55-5c10-4f4e-987a-20a11f4ec9fc"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("108bf3a5-da64-4d9f-9e8f-67b6c549f1b2"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("cc7ea164-502a-47df-a6fb-6e954c1d4392"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entity.GameGenre", b =>
                {
                    b.HasOne("GameStore.Data.Entity.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entity.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Entity.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Data.Entity.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entity.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Entity.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Entity.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("GameStore.Data.Entity.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Entity.Genre", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Data.Entity.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
