// <auto-generated />
using System;
using GameStore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240831164545_Add-orders")]
    partial class Addorders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("02e73b48-bf3e-45df-a107-c65f302ce8dc"),
                            Name = "RTS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("03e73b48-bf3e-45df-a107-c65f302ce8dd"),
                            Name = "TBS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("04e73b48-bf3e-45df-a107-c65f302ce8de"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("05e73b48-bf3e-45df-a107-c65f302ce8df"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("07e73b48-bf3e-45df-a107-c65f302ce8e1"),
                            Name = "Rally",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("08e73b48-bf3e-45df-a107-c65f302ce8e2"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("09e73b48-bf3e-45df-a107-c65f302ce8e3"),
                            Name = "Formula",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("10e73b48-bf3e-45df-a107-c65f302ce8e4"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("12e73b48-bf3e-45df-a107-c65f302ce8e6"),
                            Name = "FPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("13e73b48-bf3e-45df-a107-c65f302ce8e7"),
                            Name = "TPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("14e73b48-bf3e-45df-a107-c65f302ce8e8"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("15e73b48-bf3e-45df-a107-c65f302ce8e9"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.OrderGame", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f2592f7-9768-4c2e-933f-50cf14b1f896"),
                            Description = "Allow customers to pay directly from their bank account to another bank account",
                            ImageUrl = "https://cdn5.vectorstock.com/i/1000x1000/41/09/payment-terminal-icon-simple-style-vector-22764109.jpg",
                            Title = "Bank"
                        },
                        new
                        {
                            Id = new Guid("94a5703d-6ba8-42e5-82d7-7fcfcb050ab4"),
                            Description = "The ibox system is built to provide maximum protection for client and user data",
                            ImageUrl = "https://a0.anyrgb.com/pngimg/990/1580/ibox-new-payment-terminal-privatbank-rates-chernihiv-selfservice-ukraine-value-cash.png",
                            Title = "IBox terminal"
                        },
                        new
                        {
                            Id = new Guid("5cdfec58-07db-499c-85ae-3ebcbafb5b5d"),
                            Description = "Visa is a global payment technology business that connects customers, businesses, banks, and governments, enabling them to use digital currency instead of cash or checks",
                            ImageUrl = "https://www.visa.com.au/dam/VCOM/regional/ve/romania/blogs/hero-image/visa-logo-800x450.jpg",
                            Title = "Visa"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01f73b48-bf3e-45df-a107-c65f302ce8fa"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("02f73b48-bf3e-45df-a107-c65f302ce8fb"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("03f73b48-bf3e-45df-a107-c65f302ce8fc"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("04f73b48-bf3e-45df-a107-c65f302ce8fd"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.OrderGame", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Order", "Order")
                        .WithMany("OrderGames")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("OrderGames")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Order", b =>
                {
                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
