// <auto-generated />
using System;
using GameStore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20241014184934_Updated new dbsets")]
    partial class Updatednewdbsets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Context.Entity.BannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BannedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BannedTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuantityPerUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<int>("UnitsOnOrder")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("GameId", "GenreId")
                        .IsUnique();

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("GameId", "PlatformId")
                        .IsUnique();

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("02e73b48-bf3e-45df-a107-c65f302ce8dc"),
                            Name = "RTS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("03e73b48-bf3e-45df-a107-c65f302ce8dd"),
                            Name = "TBS",
                            ParentGenreId = new Guid("01e73b48-bf3e-45df-a107-c65f302ce8db")
                        },
                        new
                        {
                            Id = new Guid("04e73b48-bf3e-45df-a107-c65f302ce8de"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("05e73b48-bf3e-45df-a107-c65f302ce8df"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("07e73b48-bf3e-45df-a107-c65f302ce8e1"),
                            Name = "Rally",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("08e73b48-bf3e-45df-a107-c65f302ce8e2"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("09e73b48-bf3e-45df-a107-c65f302ce8e3"),
                            Name = "Formula",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("10e73b48-bf3e-45df-a107-c65f302ce8e4"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("4ebd532a-2c0f-4b3a-96c3-06d77f7a432d")
                        },
                        new
                        {
                            Id = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("12e73b48-bf3e-45df-a107-c65f302ce8e6"),
                            Name = "FPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("13e73b48-bf3e-45df-a107-c65f302ce8e7"),
                            Name = "TPS",
                            ParentGenreId = new Guid("8ba799e7-6a4a-4302-b6cc-e5ab871cd8aa")
                        },
                        new
                        {
                            Id = new Guid("14e73b48-bf3e-45df-a107-c65f302ce8e8"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("15e73b48-bf3e-45df-a107-c65f302ce8e9"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.OrderGame", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f2592f7-9768-4c2e-933f-50cf14b1f896"),
                            Description = "Allow customers to pay directly from their bank account to another bank account",
                            ImageUrl = "https://cdn5.vectorstock.com/i/1000x1000/41/09/payment-terminal-icon-simple-style-vector-22764109.jpg",
                            Title = "Bank"
                        },
                        new
                        {
                            Id = new Guid("94a5703d-6ba8-42e5-82d7-7fcfcb050ab4"),
                            Description = "The ibox system is built to provide maximum protection for client and user data",
                            ImageUrl = "https://a0.anyrgb.com/pngimg/990/1580/ibox-new-payment-terminal-privatbank-rates-chernihiv-selfservice-ukraine-value-cash.png",
                            Title = "IBox terminal"
                        },
                        new
                        {
                            Id = new Guid("5cdfec58-07db-499c-85ae-3ebcbafb5b5d"),
                            Description = "Visa is a global payment technology business that connects customers, businesses, banks, and governments, enabling them to use digital currency instead of cash or checks",
                            ImageUrl = "https://www.visa.com.au/dam/VCOM/regional/ve/romania/blogs/hero-image/visa-logo-800x450.jpg",
                            Title = "Visa"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f088f367-445f-4174-973e-6485c8873f9b"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("56c96b36-4313-4039-8155-6a48135cd1a6"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("5123946b-4666-40e4-9eae-961527ce0a73"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3033"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("c480ff7a-0ae6-422d-960f-0774dcc04cd3"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("9d276ad0-cc81-421f-a4ee-e5718233a665"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("eafe705c-c3d9-4717-a71f-47ac455a385f"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("34080a89-1998-49d0-84e7-8891d7309b6c"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            RoleId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030")
                        },
                        new
                        {
                            Id = new Guid("a63c2127-a9aa-4904-b445-c4d12b5cebae"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("8b4ee723-8f5c-4594-89b8-29daa4f52471"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("4a2b1a0f-9921-4015-b6ce-d27a7cd7a087"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("e5b8e26d-0b3d-4d00-bad3-fec98da6cb68"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("8abaeedc-5eb8-449c-95bb-504ffef31ad3"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("2d9a6e53-3240-415a-b49c-8e5f32d83c47"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            RoleId = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5")
                        },
                        new
                        {
                            Id = new Guid("0019bfaa-6339-4747-bfdd-f24ffd37e7e9"),
                            AccessType = 1,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3033"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("131cab9a-eef6-4836-85e1-86102abf9063"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("cf664bfe-6f5f-43d9-9cce-4ac2b5247c0c"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("07b54cfc-a56e-47a4-b18f-d3a1be398f2e"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("c7a08f02-8d47-4201-af88-f6647527171d"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("65145a7d-e602-4708-99a8-09168537e01b"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("aa08c59c-9db5-4cf5-a3c2-07969b698b3a"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            RoleId = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0")
                        },
                        new
                        {
                            Id = new Guid("f65355cd-56a2-486c-84f3-09373e68d56f"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("20449ac2-d11d-438e-be04-b9c1babf424f"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("6ea8e687-03a1-42f1-96a4-160407b8028a"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3033"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("7d7edb67-95af-40f5-b5c2-0bd1f67ee371"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("2f256bf1-18f4-40c5-8c72-18d351d2e535"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("ff6b24dc-c5d6-4d5d-8cb0-e5fd76d9ec88"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("e8eacfde-7882-4e9b-8a71-61af3c609e8e"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce")
                        },
                        new
                        {
                            Id = new Guid("88601979-45c1-4b4f-98f5-fe0da0ee8e93"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("2ca38656-0ee8-4973-aacc-22f847e3abae"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("55d7ba56-f132-49ab-b282-64b4ccf7e3fe"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3033"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("ae506a43-38f3-4e37-85dc-a94ddf8e5c4d"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("4767f2f8-f92c-4661-9a78-95b0b6754f4d"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("69f4a664-abb4-4c8d-b103-9207c1841482"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        },
                        new
                        {
                            Id = new Guid("a3688480-8a8f-44da-a30f-16ecae13a598"),
                            AccessType = 0,
                            ResourceId = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            RoleId = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee")
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01f73b48-bf3e-45df-a107-c65f302ce8fa"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("02f73b48-bf3e-45df-a107-c65f302ce8fb"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("03f73b48-bf3e-45df-a107-c65f302ce8fc"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("04f73b48-bf3e-45df-a107-c65f302ce8fd"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3031"),
                            Name = "Games"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3032"),
                            Name = "Orders"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3033"),
                            Name = "Comments"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3034"),
                            Name = "Genres"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3035"),
                            Name = "Platforms"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3036"),
                            Name = "Publishers"
                        },
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3037"),
                            Name = "Users"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d27fc764-f53d-40cb-a6f9-629f433c3030"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("aad1fa8c-b73f-40a4-8a3d-84130cf352c5"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("68768561-0ed1-4cfc-a43b-7c74e635dec0"),
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = new Guid("155f3369-d8da-4b69-8e90-72e8ac6021ce"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("155f3369-d8da-4b69-8e90-72e8ac7022ee"),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.BannedUser", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.User", "User")
                        .WithMany("BannedUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Comment", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId");

                    b.Navigation("Game");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GameGenre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.OrderGame", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Order", "Order")
                        .WithMany("OrderGames")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Game", "Game")
                        .WithMany("OrderGames")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Permission", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Role", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.UserRole", b =>
                {
                    b.HasOne("GameStore.Data.Context.Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Context.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Comment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");

                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Genre", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Order", b =>
                {
                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GameStore.Data.Context.Entity.User", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("Roles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
